# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
