# Use postgres/example user/password credentials
version: '3.9'
services:
  postgres:
    init: true
    hostname: postgres
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
