# Use postgres/example user/password credentials
version: '3.9'
services:
  postgis-in:
    init: true
    hostname: postgres-in
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/

# postgis-out:
#   init: true
#   hostname: postgres-out
#   image: postgis/postgis:16-3.4
#   restart: always
#   environment:
#     - POSTGRES_USER=root
#     - POSTGRES_PASSWORD=root
#     - POSTGRES_DB=dbext
#   ports:
#     - '5433:5432'
# 