version: '3.9'
services:
  postgis:
    init: true
    hostname: postgres
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/

  oracle:
    hostname: oracle
    container_name: oracle
    build: dockerimages/oracle11g
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "${OUT_ORA1_PORT}:${OUT_ORA1_PORT}"
    volumes:
      - ./data/:/data
