version: '3.9'
services:
  postgis:
    init: true
    hostname: postgis
    container_name: postgis
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - ./data/:/data

  oracle:
    hostname: oracle
    container_name: oracle
    image: w4bo/oracle11g-java:latest
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "${OUT_ORA1_PORT}:1521"
    volumes:
      - ./oracle11g/:/docker-entrypoint-initdb.d/
      - ./data/:/data
