version: '3.9'
services:
  postgis:
    init: true
    hostname: postgis
    container_name: postgis
    image: postgis/postgis:17-3.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - ./data/:/data

  oracledb:
    hostname: oracledb
    container_name: oracledb
    image: w4bo/oracle11g-java:latest
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "${OUT_ORA1_PORT}:1521"
    volumes:
      - ./oracle11g/:/docker-entrypoint-initdb.d/
      - ./data/:/data

  mongodb:
    image: mongo:8.0.5
    ports:
      - "${MONGO_PORT}:27017"
  
  orion:
    image: fiware/orion:3.12.0
    ports:
      - "1026:1026"
    command: -corsOrigin __ALL -dbhost mongodb -inReqPayloadMaxSize 5000000